package com.example.census.entity

/**
 * Represents a person inside the census application.
 * The identifier is generated by the data layer when the entity is stored.
 */
data class Person(
    var id: Int = 0,
    var name: String,
    var age: Int,
    var gender: String
)
